---
- hosts: group1
  tasks:
  - name: installing httpd
    yum:
      name: httpd
      state: present
  - name: started the httpd service
    service:
      name: httpd
      state: started
  - name: copying the html files
    copy: src=/tmp/index.html dest=/var/www/html/index.html
